### ISSUE TITLE
Sonoff RF Bridge 433 Support

### ISSUE THREAD

**Issue by deon-wentzel** [MacWyznawca/homebridge-mqtt-switch-tasmota#13]
Hi

Will this plugin support the Sonoff RF Bridge 433?

**Comment by miskui** [comment]
Please try this: https://www.npmjs.com/package/homebridge-mqtt-sonoffrf-receiver
I will create RF sender as well.

**Comment by deon-wentzel** [comment]
Thanks

**Comment by kodibrain** [comment]
hi @miskui i have a motion sensor with on/off rf code. Can I remove the delay and add an offcode?
Thanks

**Comment by miskui** [comment]
I will update the code to be able to handle this.

**Comment by kodibrain** [comment]
That would be great. Thank you!

**Comment by miskui** [comment]
please check new version
you can contribute and merge code

**Comment by kodibrain** [comment]
Hi @miskui thank you!!! I have installed 3 motion detectors. All work fine, but when all motion detected and then one of it send off,  all go off :(

**Comment by kodibrain** [comment]
that's how I did it. I do not know how to explain this on my bad english...
in the config all 3 motiondetectors have different names, an different on/off codes.

problem example: 
motion1-on 
motion2-on
motion3-switch from on to off

then goes all motion to "OFF" although motion1 and motion2 would be on

**Comment by miskui** [comment]
please send config.json

**Comment by kodibrain** [comment]
{
      "accessory": "mqtt-sonoffrf-receiver",
      "name": "Terrasse",
      "url": "mqtt://192.168.2.5",
      "topic": "tele/sonoff_rf/RESULT",
      "username": "",
      "password": "",
      "rfcodeon": "68F70A",
      "rfcodeoff": "68F70E",
      "rfcode": "",
      "rfkey":"",
      "ondelay":"",
      "accessoryservicetype": "MotionSensor"
    },
	{
      "accessory": "mqtt-sonoffrf-receiver",
      "name": "Wohnzimmer",
      "url": "mqtt://192.168.2.5",
      "topic": "tele/sonoff_rf/RESULT",
      "username": "",
      "password": "",
      "rfcodeon": "68FF0A",
      "rfcodeoff": "68FF0E",
      "rfcode": "",
      "rfkey":"",
      "ondelay":"",
      "accessoryservicetype": "MotionSensor"
    },
	{
      "accessory": "mqtt-sonoffrf-receiver",
      "name": "Fenster",
      "url": "mqtt://192.168.2.5",
      "topic": "tele/sonoff_rf/RESULT",
      "username": "",
      "password": "",
      "rfcodeon": "76950A",
      "rfcodeoff": "76950E",
      "rfcode": "",
      "rfkey":"",
      "ondelay":"",
      "accessoryservicetype": "MotionSensor"
    },

**Comment by kodibrain** [comment]
great thank you!

**Comment by miskui** [comment]
fixed

kodibrain <notifications@github.com> ezt írta (időpont: 2018. júl. 10., K,
13:35):

**Comment by jvarneyau** [comment]
Hi Miskui. I see the link above for the Sonoff RF Bridge 433, but will this work with the standard firmware as opposed to the Tasmota firmware? Thanks.

**Comment by kodibrain** [comment]
It only works with tasmota. The Standart Firmware has no mqtt broker.
