### ISSUE TITLE
switchType

### ISSUE THREAD

**Issue by SzilagyiR** [MacWyznawca/homebridge-mqtt-switch-tasmota#2]
Hi!

First of all, thak you for the plugin!

The plugin knows only two type of switch: outlet and swich: 
"switchType": "outlet" - outlet for outlet emulation, other or empty for switch.

But I would like to use lock emulation, because now I mast say  "Hey Siri, turn on the door". It would be better to say "Hey Siri, open the door".

Can you program it to the next verion of plugin, I would donate you a beer :)

Thanks!

**Comment by jat80** [comment]
Would love the fan accessory type as well if you are able to do it. Thanks!

**Comment by gid204** [comment]
Hey this plugin is awesome thanks!
@jat80 you should be able to change the accessory to a fan straight in the Home app on your iPhone!

The reason I am messaging is to also request another switch type. I am hooking this up to my front gate so would love to be able to choose from a range of different switch types (one that included a gate opener)

Thanks!!!

**Comment by MacWyznawca** [comment]
@SzilagyiR 
Thank you!
I will think about it…

**Comment by MacWyznawca** [comment]
@jat80 
I will think about it…

**Comment by FamJohansson** [comment]
@macwyznawca 
Thanks for the great work you’re doing.
Have you implemented this switch type?

**Comment by MacWyznawca** [comment]
Yes, working in my home.

Pozdrawiam!

— 
Jaromir (@MacWyznawca)
iOS, macOS and FileMaker developer
<macwyznawca.pl> | qart@me.com 
tel./iMessages: 501 133 157

**Comment by jeylites** [comment]
what is the list of switch type that could be used besides "outlet"?

**Comment by MacWyznawca** [comment]
Outlet or Switch only.

Pozdrawiam!

— 
Jaromir (@MacWyznawca)
iOS, macOS, HomeKit, FileMaker developer
<lugallery.com> <faqt.pl> <macwyznawca.pl>
tel./iMessages: +48 501 133 157
