### ISSUE TITLE
Support for Sonoff 4CH Pro?

### ISSUE THREAD

**Issue by timhng** [MacWyznawca/homebridge-mqtt-switch-tasmota#23]
I see that you've added support for the Sonoff Dual. Will this also work for the Sonoff 4CH Pro? If not, is this something that you intend to add in the future?

**Comment by timhng** [comment]
To answer my own question - this excellent plugin already supports the 4CH Pro. Just need to Have a separate configuration for each channel in the config.json file. The Topic should be the same ifor all channels but command POWER1, POWER2 etc.

**Comment by FamJohansson** [comment]
@timhng 
Do you have an example config.jason that you can add here?
