### ISSUE TITLE
Inform about state Lights after switch on wall physical button

### ISSUE THREAD

**Issue by radebebek** [MacWyznawca/homebridge-mqtt-switch-tasmota#28]
Hello All,

I have this scheme wiring: http://prntscr.com/i0qrfb

I used homebridge plugin and iphone app HOME and I have problem about inform state.

Example:

State Lights on HOME app is OFF.
Turn on Lights with HOME app on R1 relay, snd Sonoff PRO switch reley and Lights is ON. On app HOME change state to ON.
When I pressing physical key "WALL SWITHC" Disconnect Electric Cricuit and turn off Light.
State continue ON on HomeAPP.
How to inform app that state is change? Can you help me this plugin?
Rade

**Comment by OnilMr** [comment]
I have the same issue. 
I don’t have the sonoff pluged to the wall, but when I press the home app it says “ON” when it should stay off.

**Comment by Kepete** [comment]
Any fix for this issue?

**Comment by acoolax** [comment]
I have the same issue.

**Comment by DaPeace** [comment]
Same here.. the status is not changing and im not sure if that might not be a tasmota-problem.

**Comment by radebebek** [comment]
Can you somebody fix it to another way?
