### ISSUE TITLE
I do not get communication between homebridge and mqtt

### ISSUE THREAD

**Issue by ZoltXs** [MacWyznawca/homebridge-mqtt-switch-tasmota#30]
I can not get homebridge to communicate with mosquitto server, everything is well configured without error and I can not do anything, can someone help me ???
![44921631-fb7d-4762-aea5-8062a86f3784](https://user-images.githubusercontent.com/3195969/36075531-ab187852-0f50-11e8-9a46-82f7d67b6912.jpeg)
![1e093b9e-a1b8-446f-a6ce-75a9a15aecae](https://user-images.githubusercontent.com/3195969/36075532-ab38204e-0f50-11e8-907e-b3441136d211.jpeg)

**Comment by stofakiller** [comment]
i have the same issue, how did you solve this?
