### ISSUE TITLE
Is this the right plugin for Sonoff SV?

### ISSUE THREAD

**Issue by ceraz68** [MacWyznawca/homebridge-mqtt-switch-tasmota#35]
Hi I was wondering if this is the right homebridge plugin to use for a Sonoff SV. I plan to use it as a garage door opener. The relay feature of the sonoff emulates a standard push button to open/close the door.

As far as I understand, I should use the pulsetime setting in tasmota console to last 1 second to emulate the standard garage door push button.

Not to sure whether all these settings from the homebridge-mqtt-switch-tasmota plugin are relevant for a Sonoff SV:
		"topics": {
			"statusGet": "stat/sonoff/RESULT",
			"statusSet": "cmnd/sonoff/POWER",
			"stateGet": "tele/sonoff/STATE"
		},
		"onValue": "ON",
		"offValue": "OFF",
	
		"activityTopic": "tele/sonoff/LWT",
        "activityParameter": "Online",
    
		"startCmd": "cmnd/sonoff/TelePeriod",
		"startParameter": "60",

Thanks for any advice

PS: I use the mqtt-power-consumption-log-tasmota plugin for my sonoff pow so I am familiar with MQTT etc.

**Comment by ceraz68** [comment]
OK got my SONOFF SV working with this plugin and minimal settings as below. 

I set the SONOFF pulsetime to 10 to emulate a garage door push button
"Hey Siri, turn on garage" works well to command the garage motor.

Just need to resolve an issue that the Sonoff relay triggers ON after a power restart even though I changed the sonoff poweronstate is set to 0. Not a good idea to have a garage door open after power failure recovery.


{
"accessory": "mqtt-switch-tasmota",
"name": "Garage",
"url": "mqtt://ip_address",
"username": "username",
"password": "password",
"topics": {
   "statusGet": "stat/sonoffsv/POWER",
   "statusSet": "cmnd/sonoffsv/POWER"
  }
},

**Comment by ceraz68** [comment]
Leave a comment

**Comment by aquadat0r** [comment]
Would be great to rather say" Siri, Open Garage Door".  Are you also using a reedswitch to determine the state of the garage door?

**Comment by ceraz68** [comment]
I'm using a separate door contact (eve elgato) to validate whether the door is open or closed. I thought it was "safer" not to mix two functionalities in one device.
You can only turn on switches. It may be possible to teach siri to replace "hey siri, open garage" to an homekit instruction "turn on garage" but I don't know if that is possible.
