### ISSUE TITLE
add a second Sonoff 

### ISSUE THREAD

**Issue by FamJohansson** [MacWyznawca/homebridge-mqtt-switch-tasmota#5]
How can I add a second Sonoff device in the config.json file?

"accessories": [
    	{
				"accessory": "mqtt-switch-tasmota",
				"name": "sonoff",

				"url": "mqtt://Homebridge",
				"username": "DVES_USER",
				"password": "DVES_PASS",

				"topics": {
				"statusGet": "stat/sonoff/RESULT",
				"statusSet": "cmnd/sonoff/POWER",
				"stateGet": "tele/sonoff/STATE"
									},
				"onValue": "ON",
				"offValue": "OFF",

				"activityTopic": "tele/sonoff/LWT",
				"activityParameter": "Online",

				"startCmd": "cmnd/sonoff/TelePeriod",
				"startParameter": "60",

				"manufacturer": "ITEAD",
				"model": "Sonoff",
				"serialNumberMAC": ""
			},
			{
				"accessory": "mqtt-switch-tasmota",
				"name": "taklampe",

				"url": "mqtt://Homebridge",
				"username": "DVES_USER",
				"password": "DVES_PASS",

				"topics": {
				"statusGet": "stat/taklampe/RESULT",
				"statusSet": "cmnd/taklampePOWER",
				"stateGet": "tele/taklampe/STATE"
									},
				"onValue": "ON",
				"offValue": "OFF",

				"activityTopic": "tele/taklampe/LWT",
				"activityParameter": "Online",

				"startCmd": "cmnd/taklampe/TelePeriod",
				"startParameter": "60",

				"manufacturer": "ITEAD",
				"model": "Sonoff",
				"serialNumberMAC": ""
			}
And how to configure Sonoff settings

**Comment by FamJohansson** [comment]
If i turn the second sonoff on or off via web page it turns on and off and  I Can see the status changes in Apple Home app. If I turn it on or off via Apple Home app the status is changed in the Apple home app but the sonoff is not turning on or off.

**Comment by jeylites** [comment]
@FamJohansson I'm in the same situation. Have you managed to solve it?

**Comment by FamJohansson** [comment]
Hi, I have not managed to resolve this.

**Comment by FamJohansson** [comment]
Is there anyone who has a solution to this?

**Comment by FamJohansson** [comment]
Can @MacWyznawca look at this?

**Comment by MacWyznawca** [comment]
First working? Config file looks ok.

Can You check console log via web on second? That model? Basic?

**Comment by FamJohansson** [comment]
@macwyznawc Both is basic

**Comment by deon-wentzel** [comment]
Hi, I have about 15 Sonoff working perfectly. Have you changed the MQTT name on Sonoff to taklampe via the Web Interface on the Sonoff Device.

**Comment by FamJohansson** [comment]
Hello again,

I was missing a /  in this line. 
			"statusSet": "cmnd/taklampePOWER",
			
Thanks for all the help.

Case closed.
